name: Build

on: [create]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up Nuget
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Restore Nuget package
        run: nuget restore
      - name: MSBuild
        run: msbuild "RH_Plugin\RH_Plugin.csproj"
      - name: Deploy
        run: yarn && yarn deploy
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          OSS_KEYID: ${{ secrets.OSS_ID }}
          OSS_KEYSECRET: ${{ secrets.OSS_SECRET }}
