name: Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Nuget
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Restore Nuget package
        run: nuget restore
      - name: MSBuild
        id: msbuild
        run: msbuild ".\NoahPlugin.sln"
      - name: Deploy
        uses: KaivnD/ali-oss-action@c7fd0c429db85219930901f602ff0ce9ea84a0a1
        with:
          oss_id: ${{ secrets.OSS_ID }}
          oss_secret: ${{ secrets.OSS_SECRET }}
          bucket: "ncfz"
          files: |
            ./RH_Plugin/bin/*.rhi=>Noah/Plugin/*.rhi
            ./RH_Plugin/bin/*.macrhi=>Noah/Plugin/*.macrhi
          dirs: |
            ./RH_Plugin/bin/channel=>Noah/Plugin/channel
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.msbuild.outputs.version }}
          release_name: Release ${{ steps.msbuild.outputs.version }}
          draft: false
          prerelease: false
      - name: Delete Comming tag
        run: |
          git push origin :${{ github.ref }}
